server.port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

spring.h2.console:
  enabled: true
  path: /h2-console


logging.level:
  org.springframework:
    security: debug
    boot: debug